version: '3'
services:
  phone_gateway:
    build: .
    container_name: phone_gateway
    image: nginx
    depends_on:
      - phone_api
      - phone_client
    links:
      - phone_api
      - phone_client
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/nginx/gateway.conf:/etc/nginx/sites-enabled/gateway.conf:ro