version: '3'

services:
  api:
    build: .
    image: 'phone_api'
    environment:
      NODE_ENV: production
      DATABASE: ${DATABASE}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:8000"

  db:
    container_name: 'phone_db'
    image: postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_USER}
    ports:
      - 5432:5432